name: env_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=40.0.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - fastapi=0.95.1
  - flit-core=3.8.0
  - fmt=9.1.0
  - gettext=0.21.1
  - glib=2.76.2
  - glib-tools=2.76.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - h11=0.14.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipykernel=6.22.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - jupyterlab_widgets=3.0.7
  - krb5=1.20.1
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=8.0.1
  - libcxx=16.0.2
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libvorbis=1.3.7
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=16.0.3
  - lz4-c=1.9.4
  - mamba=1.4.2
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=1.0.0
  - nbclient=0.7.4
  - nbconvert=7.3.1
  - nbconvert-core=7.3.1
  - nbconvert-pandoc=7.3.1
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - openssl=3.1.0
  - packaging=23.1
  - pandas=2.0.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.7
  - pygments=2.15.1
  - pyobjc-core=9.1.1
  - pyobjc-framework-cocoa=9.1.1
  - pyopenssl=23.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytest=7.3.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - qtconsole=5.4.2
  - qtconsole-base=5.4.2
  - qtpy=2.3.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ruamel.yaml=0.17.22
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=67.7.2
  - sip=6.7.9
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - starlette=0.26.1
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - uvicorn=0.22.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - xz=5.2.10
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
    - aiobotocore==2.5.0
    - aiohttp==3.8.4
    - aiohttp-retry==2.8.3
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - amqp==5.1.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asyncssh==2.13.1
    - atpublic==3.1.1
    - billiard==3.6.4.0
    - boto3==1.26.76
    - botocore==1.29.76
    - celery==5.2.7
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - configobj==5.0.8
    - dictdiffer==0.9.0
    - diskcache==5.6.1
    - distro==1.8.0
    - dpath==2.1.5
    - dulwich==0.21.5
    - dvc==2.56.0
    - dvc-data==0.47.2
    - dvc-http==2.30.2
    - dvc-objects==0.21.2
    - dvc-render==0.4.0
    - dvc-s3==2.22.0
    - dvc-studio-client==0.8.0
    - dvc-task==0.2.1
    - filelock==3.12.0
    - flatten-dict==0.4.2
    - flufl-lock==7.1.1
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - funcy==2.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - grandalf==0.8
    - hydra-core==1.3.2
    - iterative-telemetry==0.0.8
    - jmespath==1.0.1
    - kombu==5.2.4
    - markdown-it-py==2.2.0
    - mdurl==0.1.2
    - multidict==6.0.4
    - nanotime==0.5.2
    - networkx==3.1
    - omegaconf==2.3.0
    - orjson==3.8.11
    - pathspec==0.11.1
    - pydot==1.4.2
    - pygit2==1.12.0
    - pygtrie==2.5.0
    - pyparsing==3.0.9
    - rich==13.3.5
    - s3fs==2023.4.0
    - s3transfer==0.6.0
    - scmrepo==1.0.3
    - shortuuid==1.0.11
    - shtab==1.6.1
    - smmap==5.0.0
    - sqltrie==0.3.1
    - tabulate==0.9.0
    - tomlkit==0.11.8
    - vine==5.0.0
    - voluptuous==0.13.1
    - wrapt==1.15.0
    - yarl==1.9.2
    - zc-lockfile==3.0.post1
