name: env_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=23.3.1
  - fastapi=0.95.1
  - jupyter=1.0.0
  - jupyterlab=3.5.3
  - numpy=1.24.3
  - pandas=1.5.3
  - pysocks=1.7.1
  - pytest=7.3.1
  - python=3.8.16
  - scikit-learn=1.2.2
  - uvicorn=0.22.0
  - pip=23.1.2
  - pip:
      - dvc==2.56.0
      - dvc-s3==2.22.0
